on:
  push:
    branches:
      - main

jobs:
  younggeon.kim:
    runs-on: ubuntu-latest
    steps:
      - uses: adityakar/workflow-dispatcher@v1.0
        with:
          event_type: opened
          owner: dungsil
          repo: "younggeon.kim"
          token: ${{ secrets.GH_TOKEN }}
          wait_time: 120 # 2분
