on:
  push:
    branches:
      - main

jobs:
  younggeon_kim:
    runs-on: ubuntu-latest
    steps:
      - uses: adityakar/workflow-dispatcher@v1.0
        with:
          event_type: push-update-dispatcher
          owner: dungsil
          repo: "younggeon.kim"
          token: ${{ secrets.GH_TOKEN }}
          wait_time: 120 # 2분
          client_payload: '{ "ref": "main" }'
